ami = "ami-0b898040803850657"
instance_type = "t2.micro"
key_name = ""
aws_region = "us-east-1"
sg_name = "demo-sg-name"
vpc_cidr_block = ""
public_subnet_cidr_block = ""
private_subnet_cidr_block = ""